language: ruby
rvm:
- 2.3.4

cache: bundler # speed up

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
- bundle exec jekyll build

addons:
  ssh_known_hosts: prod.cmlteam.com

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

#env:
#  global:
#  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

before_deploy:
- openssl aes-256-cbc -K $encrypted_084ba45aab19_key -iv $encrypted_084ba45aab19_iv
  -in deploy_rsa.enc
  -out /tmp/deploy_rsa -d
- chmod 600 /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script:
  - cd _site ; scp -i /tmp/deploy_rsa -C -r * apps1@prod.cmlteam.com:~/www-training


