title: "Best workshops and trainings at CML Consulting"
description: > # this means to ignore newlines until "baseurl:"
  "Best workshops and trainings on Blockchain, Data Science, Chatbots, Java, Hackathons from leading ukrainian startup CML Consulting"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://training.cmlteam.com" # the base hostname & protocol for your site

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url:
  - title: linkedin
    url: https://www.linkedin.com/company-beta/18045280/
  - title: github
    url: https://github.com/CMLTeam
  - title: instagram
    url: https://www.instagram.com/cmlteam/

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty